# Generated by Django 4.2.1 on 2023-06-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='raw_file',
            new_name='file',
        ),
    ]
