# Generated by Django 4.2.1 on 2023-06-30 15:50

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_raw_file_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='snapit/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
